spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accidentmap
    username: postgres
    password: 1234

  jwt:
    secret:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
