spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accidentmap
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
